displayName: "GitHub Actions Provider"
description: "OIDC provider for GitHub Actions"
attributeMapping:
  google.subject: assertion.sub
  attribute.actor: assertion.actor
  attribute.repository: assertion.repository
oidc:
  issuerUri: "https://token.actions.githubusercontent.com"
